name: Build and Publish npm Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Use the custom action to build the npm package
      - name: Build npm Package
        uses: ./.github/actions/buildnpmpkg
        with:
          node-version: "16" # Specify the Node.js version

      # Use the custom action to publish the npm package
      - name: Publish npm Package
        uses: ./.github/actions/publishnpmpkg
        with:
          node-version: "16" # Specify the Node.js version
          registry-url: "https://npm.pkg.github.com/" # GitHub Packages registry URL
          github-token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication